# Generated by Django 5.0.3 on 2024-04-16 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
