# Generated by Django 5.0.4 on 2024-05-10 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingApp', '0007_alter_user_password_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('SchedulingApp.user',),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(default='001', max_length=3),
        ),
    ]
