# Generated by Django 5.0.3 on 2024-05-12 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingApp', '0008_supervisor_alter_section_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='assistant',
            field=models.ForeignKey(limit_choices_to={'is_assistant': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
