# Generated by Django 5.0.3 on 2024-05-14 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingApp', '0009_alter_lab_assistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('ACTSCI', 'Actuarial Science'), ('AD_LDSP', 'Administrative Leadership'), ('AFRIC', 'African & African Diaspora Studies'), ('AFAS', 'Air Force and Aerospace Studies'), ('AIS', 'American Indian Studies'), ('AMLLC', 'Ancient & Modern Languages, Literatures & Cultures'), ('ANTHRO', 'Anthropology'), ('APC', 'Applied Computing'), ('ARABIC', 'Arabic'), ('ARCH', 'Architecture'), ('ART', 'Art and Design'), ('ART_ED', 'Art Education'), ('ARTHIST', 'Art History'), ('ASTRON', 'Astronomy'), ('ATRAIN', 'Athletic Training'), ('ATM_SCI', 'Atmospheric Sciences'), ('BIO_SCI', 'Biological Sciences'), ('BME', 'Biomedical Engineering'), ('BMS', 'Biomedical Sciences'), ('BUS_ADM', 'Business Administration'), ('BUSMGMT', 'Business Management'), ('CELTIC', 'Celtic Studies'), ('CHEM', 'Chemistry and Biochemistry'), ('CHINESE', 'Chinese'), ('CIV_ENG', 'Civil & Environmental Engineering'), ('CLASSIC', 'Classics'), ('CHS', 'College of Health Sciences'), ('COMMUN', 'Communication'), ('COMSDIS', 'Communication Sciences and Disorders'), ('COMPLIT', 'Comparative Literature'), ('COMPSCI', 'Computer Science'), ('COMPST', 'Computer Studies'), ('CES', 'Conservation and Environmental Sciences'), ('COUNS', 'Counseling'), ('CRM_JST', 'Criminal Justice & Criminology'), ('CURRINS', 'Curriculum and Instruction'), ('DANCE', 'Dance'), ('DMI', 'Diagnostic Imaging'), ('DAC', 'Digital Arts and Culture'), ('ECON', 'Economics'), ('EDUC', 'Education-Interdepartmental'), ('ED_POL', 'Educational Policy and Community Studies'), ('ED_PSY', 'Educational Psychology'), ('ELECENG', 'Electrical Engineering'), ('EAS', 'Engineering and Applied Science'), ('ENGLISH', 'English'), ('EAP', 'English for Academic Purposes'), ('ETHNIC', 'Ethnic Studies, Comparative'), ('EXCEDUC', 'Exceptional Education'), ('FILMSTD', 'Film Studies'), ('FILM', 'Film, Video, Animation and New Genres'), ('FOODBEV', 'Food & Beverage Studies'), ('FRENCH', 'French'), ('FRSHWTR', 'Freshwater Sciences'), ('GEOG', 'Geography'), ('GEO_SCI', 'Geosciences'), ('GERMAN', 'German'), ('GLOBAL', 'Global Studies'), ('GRAD', 'Graduate Studies'), ('GREEK', 'Greek'), ('HCA', 'Health Care Administration'), ('HI', 'Health Care Informatics'), ('HS', 'Health Sciences'), ('HEBREW', 'Hebrew'), ('HIST', 'History'), ('HMONG', 'Hmong Studies'), ('HONORS', 'Honors College'), ('IND_REL', 'Industrial and Labor Relations'), ('IND_ENG', 'Industrial and Manufacturing Engineering'), ('INFOST', 'Information Studies'), ('INTLST', 'International Studies'), ('ITALIAN', 'Italian')], default='COMPSCI', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Winter', 'Winter'), ('Fall', 'Fall')], default='Fall', max_length=20),
        ),
        migrations.AlterField(
            model_name='lab',
            name='days',
            field=models.CharField(default='Mo We', max_length=13),
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_name',
            field=models.CharField(choices=[('001', 'Section 001'), ('002', 'Section 002'), ('003', 'Section 003')], default='001', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='days',
            field=models.CharField(default='Tu Th', max_length=13),
        ),
        migrations.AlterField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'is_instructor': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(choices=[('001', 'Section 001'), ('002', 'Section 002'), ('003', 'Section 003')], default='001', max_length=20),
        ),
    ]
