# Generated by Django 5.0.4 on 2024-05-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingApp', '0010_alter_course_department_alter_course_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='days',
            field=models.CharField(default='Mo/We', max_length=13),
        ),
    ]
